Calculated and saved phonon calculation results
materialsvirtuallab/matcalc pull request #22
Opened 2024-03-14 04:27 UTC by rul048

Our codes used to only allow the calculation and returning of thermal properties, ignoring band structure, force constants, etc. which was limited for furthur investiagtion, like dynamic stability, anharmonicity, etc.

In this update, we added several features. Phonon object was saved by default because band structure, density of states, etc. can be reconstructed from this file. We also allowed users to determine whether to calculate and save band structure, density of states and force constants. (Default to False to ensure consistency with previous code and save storage space)

## Summary

Major changes:

- feature 1: ...
- fix 1: ...

## Todos

If this is work in progress, what else needs to be done?

- feature 2: ...
- fix 2:

## Checklist

- [ ] Google format doc strings added. Check with `ruff`.
- [ ] Type annotations included. Check with `mypy`.
- [ ] Tests added for new features/fixes.
- [ ] If applicable, new classes/functions/modules have [`duecredit`](https://github.com/duecredit/duecredit) `@due.dcite` decorators to reference relevant papers by DOI ([example](https://github.com/materialsproject/pymatgen/blob/91dbe6ee9ed01d781a9388bf147648e20c6d58e0/pymatgen/core/lattice.py#L1168-L1172))

Tip: Install `pre-commit` hooks to auto-check types and linting before every commit:

```sh
pip install -U pre-commit
pre-commit install
```

2024-03-14 05:42 UTC, janosh requested changes
thanks, very sensible change!

2024-03-14 05:42 UTC, janosh commented on tests/test_phonon.py
> +        write_phonon=phonon_yaml,
i added a test for `write_phonon`. we need to cover the other new keywords as well.

2024-04-11 18:18 UTC, shyuep commented
Can we get this done soon?

2024-04-12 02:48 UTC, merged

2024-04-12 02:50 UTC, rul048 commented
> Can we get this done soon?

Thanks for your kind reminder, professor. Learned something new about pytest today.

2024-04-12 07:22 UTC, janosh commented
i think we want to aim for more comprehensive tests than were merged here.

i just pushed more stringent `PhononCalc` tests in [df738a9](https://github.com/materialsvirtuallab/matcalc/commit/df738a98494b39f252c51a0df416296181c24b4e)